//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvedio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseToTaskBar {
            get {
                return ((bool)(this["CloseToTaskBar"]));
            }
            set {
                this["CloseToTaskBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("缩略图")]
        public string ShowImageMode {
            get {
                return ((string)(this["ShowImageMode"]));
            }
            set {
                this["ShowImageMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomDisplay {
            get {
                return ((bool)(this["RandomDisplay"]));
            }
            set {
                this["RandomDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DisplayNumber {
            get {
                return ((int)(this["DisplayNumber"]));
            }
            set {
                this["DisplayNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bus {
            get {
                return ((string)(this["Bus"]));
            }
            set {
                this["Bus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB {
            get {
                return ((string)(this["DB"]));
            }
            set {
                this["DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Library {
            get {
                return ((string)(this["Library"]));
            }
            set {
                this["Library"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fc2club.com/")]
        public string Fc2Club {
            get {
                return ((string)(this["Fc2Club"]));
            }
            set {
                this["Fc2Club"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayID {
            get {
                return ((bool)(this["DisplayID"]));
            }
            set {
                this["DisplayID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayTitle {
            get {
                return ((bool)(this["DisplayTitle"]));
            }
            set {
                this["DisplayTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayDate {
            get {
                return ((bool)(this["DisplayDate"]));
            }
            set {
                this["DisplayDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayStatusBar {
            get {
                return ((bool)(this["DisplayStatusBar"]));
            }
            set {
                this["DisplayStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayFunBar {
            get {
                return ((bool)(this["DisplayFunBar"]));
            }
            set {
                this["DisplayFunBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyActivation {
            get {
                return ((bool)(this["ProxyActivation"]));
            }
            set {
                this["ProxyActivation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hitchao.gitee.io/jvediowebpage/")]
        public string Address {
            get {
                return ((string)(this["Address"]));
            }
            set {
                this["Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chao")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("识别码")]
        public string SortType {
            get {
                return ((string)(this["SortType"]));
            }
            set {
                this["SortType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortDescending {
            get {
                return ((bool)(this["SortDescending"]));
            }
            set {
                this["SortDescending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnlyShowPlay {
            get {
                return ((bool)(this["OnlyShowPlay"]));
            }
            set {
                this["OnlyShowPlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("默认")]
        public string ShowViewMode {
            get {
                return ((string)(this["ShowViewMode"]));
            }
            set {
                this["ShowViewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanGivenPath {
            get {
                return ((bool)(this["ScanGivenPath"]));
            }
            set {
                this["ScanGivenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ListenAllDir {
            get {
                return ((bool)(this["ListenAllDir"]));
            }
            set {
                this["ListenAllDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DelFromDBIfDel {
            get {
                return ((bool)(this["DelFromDBIfDel"]));
            }
            set {
                this["DelFromDBIfDel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BusEurope {
            get {
                return ((string)(this["BusEurope"]));
            }
            set {
                this["BusEurope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ScanMinFileSize {
            get {
                return ((int)(this["ScanMinFileSize"]));
            }
            set {
                this["ScanMinFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Censored")]
        public string VedioType {
            get {
                return ((string)(this["VedioType"]));
            }
            set {
                this["VedioType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-,_,cd,fhd,-fhd,_fhd")]
        public string SubSectionFeature {
            get {
                return ((string)(this["SubSectionFeature"]));
            }
            set {
                this["SubSectionFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLInfo {
            get {
                return ((bool)(this["DLInfo"]));
            }
            set {
                this["DLInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLSmallImage {
            get {
                return ((bool)(this["DLSmallImage"]));
            }
            set {
                this["DLSmallImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLBigImage {
            get {
                return ((bool)(this["DLBigImage"]));
            }
            set {
                this["DLBigImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLExtraImage {
            get {
                return ((bool)(this["DLExtraImage"]));
            }
            set {
                this["DLExtraImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLBehind {
            get {
                return ((bool)(this["DLBehind"]));
            }
            set {
                this["DLBehind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLNFO {
            get {
                return ((bool)(this["DLNFO"]));
            }
            set {
                this["DLNFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DLNum {
            get {
                return ((int)(this["DLNum"]));
            }
            set {
                this["DLNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("识别码")]
        public string SearchType {
            get {
                return ((string)(this["SearchType"]));
            }
            set {
                this["SearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActorClickShowAll {
            get {
                return ((bool)(this["ActorClickShowAll"]));
            }
            set {
                this["ActorClickShowAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowActorWithId {
            get {
                return ((bool)(this["ShowActorWithId"]));
            }
            set {
                this["ShowActorWithId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableBus {
            get {
                return ((bool)(this["EnableBus"]));
            }
            set {
                this["EnableBus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableBusEu {
            get {
                return ((bool)(this["EnableBusEu"]));
            }
            set {
                this["EnableBusEu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDB {
            get {
                return ((bool)(this["EnableDB"]));
            }
            set {
                this["EnableDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLibrary {
            get {
                return ((bool)(this["EnableLibrary"]));
            }
            set {
                this["EnableLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableFC2 {
            get {
                return ((bool)(this["EnableFC2"]));
            }
            set {
                this["EnableFC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NFOSaveComBoxIndex {
            get {
                return ((int)(this["NFOSaveComBoxIndex"]));
            }
            set {
                this["NFOSaveComBoxIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("识别码")]
        public string AllSearchType {
            get {
                return ((string)(this["AllSearchType"]));
            }
            set {
                this["AllSearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotice {
            get {
                return ((bool)(this["ShowNotice"]));
            }
            set {
                this["ShowNotice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckUpdate {
            get {
                return ((bool)(this["AutoCheckUpdate"]));
            }
            set {
                this["AutoCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("黑色")]
        public string Themes {
            get {
                return ((string)(this["Themes"]));
            }
            set {
                this["Themes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditMode {
            get {
                return ((bool)(this["EditMode"]));
            }
            set {
                this["EditMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLLoadUnCensored {
            get {
                return ((bool)(this["DLLoadUnCensored"]));
            }
            set {
                this["DLLoadUnCensored"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLLoadCensored {
            get {
                return ((bool)(this["DLLoadCensored"]));
            }
            set {
                this["DLLoadCensored"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLLoadEurope {
            get {
                return ((bool)(this["DLLoadEurope"]));
            }
            set {
                this["DLLoadEurope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLEnableBus {
            get {
                return ((bool)(this["DLEnableBus"]));
            }
            set {
                this["DLEnableBus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLEnableBusEu {
            get {
                return ((bool)(this["DLEnableBusEu"]));
            }
            set {
                this["DLEnableBusEu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLEnableLibrary {
            get {
                return ((bool)(this["DLEnableLibrary"]));
            }
            set {
                this["DLEnableLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLEnableDb {
            get {
                return ((bool)(this["DLEnableDb"]));
            }
            set {
                this["DLEnableDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DLEnableFC2 {
            get {
                return ((bool)(this["DLEnableFC2"]));
            }
            set {
                this["DLEnableFC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLLoadFC2 {
            get {
                return ((bool)(this["DLLoadFC2"]));
            }
            set {
                this["DLLoadFC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLLoadAll {
            get {
                return ((bool)(this["DLLoadAll"]));
            }
            set {
                this["DLLoadAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable321 {
            get {
                return ((bool)(this["Enable321"]));
            }
            set {
                this["Enable321"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDMM {
            get {
                return ((bool)(this["EnableDMM"]));
            }
            set {
                this["EnableDMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.jav321.com/")]
        public string Jav321 {
            get {
                return ((string)(this["Jav321"]));
            }
            set {
                this["Jav321"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.dmm.co.jp/")]
        public string DMM {
            get {
                return ((string)(this["DMM"]));
            }
            set {
                this["DMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBCookie {
            get {
                return ((string)(this["DBCookie"]));
            }
            set {
                this["DBCookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BasePicPath {
            get {
                return ((string)(this["BasePicPath"]));
            }
            set {
                this["BasePicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FlowNum {
            get {
                return ((int)(this["FlowNum"]));
            }
            set {
                this["FlowNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Baidu_API_KEY {
            get {
                return ((string)(this["Baidu_API_KEY"]));
            }
            set {
                this["Baidu_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Baidu_SECRET_KEY {
            get {
                return ((string)(this["Baidu_SECRET_KEY"]));
            }
            set {
                this["Baidu_SECRET_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_BaiduAI {
            get {
                return ((bool)(this["Enable_BaiduAI"]));
            }
            set {
                this["Enable_BaiduAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TitleShowTranslate {
            get {
                return ((bool)(this["TitleShowTranslate"]));
            }
            set {
                this["TitleShowTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlotShowTranslate {
            get {
                return ((bool)(this["PlotShowTranslate"]));
            }
            set {
                this["PlotShowTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TL_YOUDAO_APIKEY {
            get {
                return ((string)(this["TL_YOUDAO_APIKEY"]));
            }
            set {
                this["TL_YOUDAO_APIKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TL_YOUDAO_SECRETKEY {
            get {
                return ((string)(this["TL_YOUDAO_SECRETKEY"]));
            }
            set {
                this["TL_YOUDAO_SECRETKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_TL_YOUDAO {
            get {
                return ((bool)(this["Enable_TL_YOUDAO"]));
            }
            set {
                this["Enable_TL_YOUDAO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TL_BAIDU_APIKEY {
            get {
                return ((string)(this["TL_BAIDU_APIKEY"]));
            }
            set {
                this["TL_BAIDU_APIKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TL_BAIDU_SECRETKEY {
            get {
                return ((string)(this["TL_BAIDU_SECRETKEY"]));
            }
            set {
                this["TL_BAIDU_SECRETKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_TL_BAIDU {
            get {
                return ((bool)(this["Enable_TL_BAIDU"]));
            }
            set {
                this["Enable_TL_BAIDU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActorEditMode {
            get {
                return ((bool)(this["ActorEditMode"]));
            }
            set {
                this["ActorEditMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableWindowFade {
            get {
                return ((bool)(this["EnableWindowFade"]));
            }
            set {
                this["EnableWindowFade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayStamp {
            get {
                return ((bool)(this["DisplayStamp"]));
            }
            set {
                this["DisplayStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_MatchAllWord {
            get {
                return ((bool)(this["Search_MatchAllWord"]));
            }
            set {
                this["Search_MatchAllWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("识别码")]
        public string Search_Type {
            get {
                return ((string)(this["Search_Type"]));
            }
            set {
                this["Search_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Search_Content {
            get {
                return ((string)(this["Search_Content"]));
            }
            set {
                this["Search_Content"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("普通")]
        public string Search_Pattern {
            get {
                return ((string)(this["Search_Pattern"]));
            }
            set {
                this["Search_Pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Opacity_Main {
            get {
                return ((double)(this["Opacity_Main"]));
            }
            set {
                this["Opacity_Main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FFMPEG_Path {
            get {
                return ((string)(this["FFMPEG_Path"]));
            }
            set {
                this["FFMPEG_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchImmediately {
            get {
                return ((bool)(this["SearchImmediately"]));
            }
            set {
                this["SearchImmediately"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ActorDisplayNum {
            get {
                return ((int)(this["ActorDisplayNum"]));
            }
            set {
                this["ActorDisplayNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ScreenShotNum {
            get {
                return ((int)(this["ScreenShotNum"]));
            }
            set {
                this["ScreenShotNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("中文")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MovieStyle_InMargin_UD {
            get {
                return ((int)(this["MovieStyle_InMargin_UD"]));
            }
            set {
                this["MovieStyle_InMargin_UD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MovieStyle_InMargin_LR {
            get {
                return ((int)(this["MovieStyle_InMargin_LR"]));
            }
            set {
                this["MovieStyle_InMargin_LR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisPlayNoStamp {
            get {
                return ((bool)(this["DisPlayNoStamp"]));
            }
            set {
                this["DisPlayNoStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisPlayCHS {
            get {
                return ((bool)(this["DisPlayCHS"]));
            }
            set {
                this["DisPlayCHS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisPlayOutFlow {
            get {
                return ((bool)(this["DisPlayOutFlow"]));
            }
            set {
                this["DisPlayOutFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisPlayHDV {
            get {
                return ((bool)(this["DisPlayHDV"]));
            }
            set {
                this["DisPlayHDV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MovieStyle_OutMargin_UD {
            get {
                return ((int)(this["MovieStyle_OutMargin_UD"]));
            }
            set {
                this["MovieStyle_OutMargin_UD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MovieStyle_OutMargin_LR {
            get {
                return ((int)(this["MovieStyle_OutMargin_LR"]));
            }
            set {
                this["MovieStyle_OutMargin_LR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD700")]
        public string Selected_BorderBrush {
            get {
                return ((string)(this["Selected_BorderBrush"]));
            }
            set {
                this["Selected_BorderBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#90EE90")]
        public string Selected_Background {
            get {
                return ((string)(this["Selected_Background"]));
            }
            set {
                this["Selected_Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MovieStyle_WordMargin_UD {
            get {
                return ((int)(this["MovieStyle_WordMargin_UD"]));
            }
            set {
                this["MovieStyle_WordMargin_UD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MovieStyle_WordMargin_LR {
            get {
                return ((int)(this["MovieStyle_WordMargin_LR"]));
            }
            set {
                this["MovieStyle_WordMargin_LR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_ID_Bold {
            get {
                return ((bool)(this["Font_ID_Bold"]));
            }
            set {
                this["Font_ID_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_ID_Italic {
            get {
                return ((bool)(this["Font_ID_Italic"]));
            }
            set {
                this["Font_ID_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_ID_UnderLine {
            get {
                return ((bool)(this["Font_ID_UnderLine"]));
            }
            set {
                this["Font_ID_UnderLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Font_ID_Size {
            get {
                return ((int)(this["Font_ID_Size"]));
            }
            set {
                this["Font_ID_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体")]
        public string Font_ID_Family {
            get {
                return ((string)(this["Font_ID_Family"]));
            }
            set {
                this["Font_ID_Family"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_Date_Bold {
            get {
                return ((bool)(this["Font_Date_Bold"]));
            }
            set {
                this["Font_Date_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_Date_Italic {
            get {
                return ((bool)(this["Font_Date_Italic"]));
            }
            set {
                this["Font_Date_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_Date_UnderLine {
            get {
                return ((bool)(this["Font_Date_UnderLine"]));
            }
            set {
                this["Font_Date_UnderLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Font_Date_Size {
            get {
                return ((int)(this["Font_Date_Size"]));
            }
            set {
                this["Font_Date_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体")]
        public string Font_Date_Family {
            get {
                return ((string)(this["Font_Date_Family"]));
            }
            set {
                this["Font_Date_Family"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_Title_Bold {
            get {
                return ((bool)(this["Font_Title_Bold"]));
            }
            set {
                this["Font_Title_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_Title_Italic {
            get {
                return ((bool)(this["Font_Title_Italic"]));
            }
            set {
                this["Font_Title_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font_Title_UnderLine {
            get {
                return ((bool)(this["Font_Title_UnderLine"]));
            }
            set {
                this["Font_Title_UnderLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Font_Title_Size {
            get {
                return ((int)(this["Font_Title_Size"]));
            }
            set {
                this["Font_Title_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体")]
        public string Font_Title_Family {
            get {
                return ((string)(this["Font_Title_Family"]));
            }
            set {
                this["Font_Title_Family"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int SmallImage_Height {
            get {
                return ((int)(this["SmallImage_Height"]));
            }
            set {
                this["SmallImage_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int SmallImage_Width {
            get {
                return ((int)(this["SmallImage_Width"]));
            }
            set {
                this["SmallImage_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string BigImage_Height {
            get {
                return ((string)(this["BigImage_Height"]));
            }
            set {
                this["BigImage_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string BigImage_Width {
            get {
                return ((string)(this["BigImage_Width"]));
            }
            set {
                this["BigImage_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ExtraImage_Height {
            get {
                return ((int)(this["ExtraImage_Height"]));
            }
            set {
                this["ExtraImage_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int ExtraImage_Width {
            get {
                return ((int)(this["ExtraImage_Width"]));
            }
            set {
                this["ExtraImage_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingsIndex {
            get {
                return ((int)(this["SettingsIndex"]));
            }
            set {
                this["SettingsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ToolsIndex {
            get {
                return ((int)(this["ToolsIndex"]));
            }
            set {
                this["ToolsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VedioPlayerPath {
            get {
                return ((string)(this["VedioPlayerPath"]));
            }
            set {
                this["VedioPlayerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Statictistic_ID_Number {
            get {
                return ((int)(this["Statictistic_ID_Number"]));
            }
            set {
                this["Statictistic_ID_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Statictistic_Genre_Number {
            get {
                return ((int)(this["Statictistic_Genre_Number"]));
            }
            set {
                this["Statictistic_Genre_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Statictistic_Tag_Number {
            get {
                return ((int)(this["Statictistic_Tag_Number"]));
            }
            set {
                this["Statictistic_Tag_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Statictistic_Actor_Number {
            get {
                return ((int)(this["Statictistic_Actor_Number"]));
            }
            set {
                this["Statictistic_Actor_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataBasePath {
            get {
                return ((string)(this["DataBasePath"]));
            }
            set {
                this["DataBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenDataBaseDefault {
            get {
                return ((bool)(this["OpenDataBaseDefault"]));
            }
            set {
                this["OpenDataBaseDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
    }
}
