//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvedio {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_String() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jvedio.Resource_String", typeof(Resource_String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SMDV,BT,CCDV,CWDV,CWP,CWPBD,CWPD,CYC,DRC,DRG,DRGBD,DSAM,DSAMBD,DSAMD,HEY,HEYDOUGA,HEYZO,KP,KSC,LAF,LAFBD,LLDV,MCBD,MKBD,MKD,MXX,NIP,PT,RED,RHJ,S2M,S2MBD,S2MCR,SKY,SKYHD,SMD,SSDV,SSKP,FC2PPV,FC2,GACHI,GACHIG,NALGASCLUB,LL,KG,HAMESAMURAI,GACHIP 的本地化字符串。
        /// </summary>
        internal static string Bubing {
            get {
                return ResourceManager.GetString("Bubing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Jvedio {
            get {
                object obj = ResourceManager.GetObject("Jvedio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ABBA,ABP,ABS,AD,ADN,ADV,ADVF,ADVO,ADZ,AED,AEDVD,AGEMIX,AJVR,AKHO,ALB,ALD,AMBI,AMD,ANB,AND,ANND,ANX,ANZI,AOZ,AP,APAA,APAK,APKH,APNS,ARA,ARATHD,ARD,ARM,ARMD,ARMG,ARN,ARSO,ASFB,AST,ASW,ATAD,ATFB,ATID,ATKD,ATOM,AUKG,AUKS,AV,AVD,AVGP,AVKH,AVOP,AVOPVR,AVSA,AVVR,AW,AWD,AWT,BAGBD,BAZX,BBAN,BBBN,BBI,BC,BCDP,BCPV,BDA,BDMILD,BDSR,BEB,BF,BGSD,BIB,BIG,BIJN,BIKMVR,BKD,BKSP,BLK,BLOR,BMD,BMVR,BMW,BNDV,BNSPS,BOB,BOBB,BOIN,BOKD,BOMN,BRD,BTD,BTR,BTYD,BUR,C,CABD,CABE,CACA,CADV,CAFR,CAMI,CAND,CAPI,CB,CC,CCX,CEAD,CESD,CETD,CHN,C [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Qibing {
            get {
                return ResourceManager.GetString("Qibing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3g2,3gp,3gp2,3gpp,amr,amv,asf,avi,bdmv,bik,d2v,divx,drc,dsa,dsm,dss,dsv,evo,f4v,flc,fli,flic,flv,hdmov,ifo,ivf,m1v,m2p,m2t,m2ts,m2v,m4b,m4p,m4v,mkv,mp2v,mp4,mp4v,mpe,mpeg,mpg,mpls,mpv2,mpv4,mov,mts,ogm,ogv,pss,pva,qt,ram,ratdvd,rm,rmm,rmvb,roq,rpm,smil,smk,swf,tp,tpr,ts,vob,vp6,webm,wm,wmp,wmv 的本地化字符串。
        /// </summary>
        internal static string ScanVetioType {
            get {
                return ResourceManager.GetString("ScanVetioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -,_,cd 的本地化字符串。
        /// </summary>
        internal static string SubSectionFeature {
            get {
                return ResourceManager.GetString("SubSectionFeature", resourceCulture);
            }
        }
    }
}
